version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"           # React served via Nginx
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - fastapi
    environment:
      - PORT=5000
      - FASTAPI_URL=http://fastapi:8000   # <-- use service name, not localhost

  fastapi:
    build:
      context: ./ml-models/api
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./ml-models/models:/app/models   # persist ML model
      - ./ml-models/data:/app/data       # if needed
    environment:
      - MODEL_PATH=/app/models/xgb_model.pkl
