version: "3.9"

services:
  fastapi:
    build:
      context: ./ml-models
      dockerfile: api/Dockerfile
    container_name: raincheck-fastapi
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/xgb_model.pkl
      - OPENWEATHER_API_KEY=633a9d9b91294145a80cb090a154b62b
    restart: unless-stopped
    networks:
      - raincheck-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: raincheck-backend
    ports:
      - "5000:5000"
    depends_on:
      fastapi:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - PORT=5000
      - FASTAPI_URL=http://fastapi:8000
    restart: unless-stopped
    networks:
      - raincheck-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: raincheck-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
    restart: unless-stopped
    networks:
      - raincheck-network

networks:
  raincheck-network:
    driver: bridge